apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: project-x/auth
      context: auth-services
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: project-x/tickets
      context: tickets
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: project-x/orders
      context: orders
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: project-x/expirations
      context: expirations
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: project-x/payment
      context: payment-services
      docker:
        dockerfile: DockerFile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
